- first_steps.asciidoc
http://blog.sontek.net/blog/detail/turning-vim-into-a-modern-python-ide,
This link is broken, so removing this.
> Removing a Broken Link

- functions.asciidoc
The program has a method name print_max, but in the text it s refereed
mostly as print_max, except this one place.
> Corrected a Typo in Chapter function.

- modules.asciidoc
http://stackoverflow.com/questions/228181/zen-of-python
This link is also broken, if possible suggest any other link for
explanation of zen of python
> Removing broken link

- translations.md
Translation is in progress and plan to complete soon.
> Translation to Azerbaijani is started

- op_exp.md
Updating this to Python 3. 
This is a great resource, thanks for the effort.
> Fix for division operator, and added floor division operator

- programs/continue.py
raw input -> input
print' ' -> print(' ')
> updated to python 3 code

- functions.md
update print some_function() to print(some_function()), for using with python 3
> update print some_function() to print(some_function())

- programs/function_varargs.py
changes made so it is clear that:
-only first item, from calling the function is assigned to variable a.
-items 1,2,3 are assigned to *numbers
-**phonebook is dictionary, and it consists of two parts, key and value, with freely choosable names.
-return is not used, since it is explained later
- += is not used, since it is not explained.
> change function_varargs.py so it is more easily understood to beginners

- programs/oop_simplestclass.txt
I do not see the line starting with < in the book. Perhaps it should be escaped, or the < > should be removed?
> < > gets converted to html?

- oop.md
I believe this is easier to understand.
> easier to understand.

- modules.md
@swaroopch Let me know what you think about this.
> rename argument to element for clarity

- programs/backup_ver1.py
- programs/backup_ver2.py
- programs/backup_ver3.py
- programs/backup_ver4.py
Since single quotes are used in other examples, used single quotes in these examples.
> use single quotes for uniformity

- more.md
explanation of the pop method in assert part
> explanation of the pop method in assert part

- more.md
Sort key, function objects and lambda are all explained in one example. Perhaps something simpler should be used? 
Maybe something like this:  http://www.secnetix.de/olli/Python/lambda_functions.hawk. Including an example with the function, and an example  with lambda.
Thanks.
> Tried to simplify lambda explanation

- first_steps.md
Changed path of user files from c:\py to c:\py.
> c:\py on Windows

- programs/more_decorator.py
```
:!python3 /tmp/byte-of-python/programs/more_decorator.py
Write to a database or make a network call or etc.
This will be automatically retried if exception is thrown.
ERROR:retry:Attempt 1/5 failed : (('Some bad value',), {})
Traceback (most recent call last):
File "/tmp/byte-of-python/programs/more_decorator.py", line 15, in wrapper_function
return f(*args, **kwargs)
File "/tmp/byte-of-python/programs/more_decorator.py", line 37, in save_to_database
raise ValueError(arg)
ValueError: Some bad value
Write to a database or make a network call or etc.
This will be automatically retried if exception is thrown.
Press ENTER or type command to continue
```
> Catch Exception instead of using bare except.

- op_exp.md
Adding explanation + example for the bit-wise AND, OR and XOR could make it easier to understand them.
The bit-wise invert has a link for more details. I left it as it is.
> update: explanation + example for bit-wise

- .github/workflows/main.yml
https://github.com/honkit/honkit
> Migrate from GitBook to Honkit

- INSTALL.md
- Makefile
- about.md
- revision_history.md
- translation_howto.md
https://github.com/honkit/honkit
> Update text from Gitbook to Honkit

- translations.md
please accept pull request, i finished translating into Ukrainian language. Thanks again Swaroop for your outstanding work that you did so many years ago, it helped me learning and starting a new career! greetings from Vienna, Austria 
PS:Would you be interested to be invited  to the upcoming PyCon Austria conference in April 2026?
> done translation into Ukrainian language
